### ISSUE TITLE
Wrong README

### ISSUE THREAD

**Issue by yuliiakriskaia** [shtanko/Expenses-Tracking#5]
cd /path/to/project/root/
git clone https://github.com/shtanko/Expenses-Tracking
cd qm_test_proj/
docker-compose up

Your docker-compose file is located in main directory, not in qm_test_proj.

**Comment by shtanko** [comment]
Fixed.
Now it's like this:
```
cd /path/to/project/root/
git clone https://github.com/shtanko/Expenses-Tracking some_directory_name
cd some_directory_name/
docker-compose up
```
